cpp-sdl2: sdl::Color Class Reference
sdl::Color Class Reference
C++ wrapping around the SDL_Color structure.
#include <color.hpp>
Public Member Functions
constexpr Color ()
Construct an sdl::Color object. Color will be black by default.
constexpr Color (Uint8 r, Uint8 g, Uint8 b, Uint8 a=255)
constexpr Color (Color const &)=default
Default copy ctor.
constexpr Color (Color &&)=default
Default move ctor.
Color (Uint32 raw, SDL_PixelFormat const &format)
Converting constructor that will initialize the color with a given 32 bit value, according to the provided PixelFormat.
Color (Uint32 raw, Uint32 format)
Converting constructor that will initialize the color with a given 32 bit value, according to the provided PixelFormat.
Color & operator= (Color const &)=default
Default copy assing operator.
Color & operator= (Color &&)=default
Default move assing operator.
Uint32 as_uint (SDL_PixelFormat const &format) const
Uint32 as_uint (Uint32 format) const
bool operator== (Color const &c) const
Return true if both colors are identical.
Static Public Member Functions
static constexpr Color White ()
static constexpr Color Black ()
static constexpr Color Red ()
static constexpr Color Green ()
static constexpr Color Blue ()
static constexpr Color Transparent ()
Friends
std::ostream & operator<< (std::ostream &stream, Color const &c)
Output stream overload that will print the value of the current color as a 4D vector of 8bit numbers.
Detailed Description
C++ wrapping around the SDL_Color structure.
Definition at line 10 of file color.hpp.
Constructor & Destructor Documentation
Color() [1/6]
constexpr sdl::Color::Color () inline
Construct an sdl::Color object. Color will be black by default.
Definition at line 14 of file color.hpp.
Referenced by Color().
Color() [2/6]
constexpr sdl::Color::Color (Uint8 r, Uint8 g, Uint8 b, Uint8 a = 255) inline
Construct an sdl Color::object with the given 8 bit color values. Alpha channel to fully opaque by default
Parameters
r 8 bit quantity of red
g 8 bit quantity of green
b 8 bit quantity of blue
a 8 bit opacity level. Default to 255 (0xff)
Definition at line 21 of file color.hpp.
References Color().
Color() [3/6]
constexpr sdl::Color::Color (Color const &) default
Default copy ctor.
Color() [4/6]
constexpr sdl::Color::Color (Color &&) default
Default move ctor.
Color() [5/6]
sdl::Color::Color (Uint32 raw, SDL_PixelFormat const & format) inline
Converting constructor that will initialize the color with a given 32 bit value, according to the provided PixelFormat.
Definition at line 33 of file color.hpp.
Color() [6/6]
sdl::Color::Color (Uint32 raw, Uint32 format) inline
Converting constructor that will initialize the color with a given 32 bit value, according to the provided PixelFormat.
Definition at line 39 of file color.hpp.
References operator=().
Member Function Documentation
as_uint() [1/2]
Uint32 sdl::Color::as_uint (SDL_PixelFormat const & format) const inline
Return the color of the current object as a 32bit number (4 bytes)
Parameters
format pixel format to use
Definition at line 55 of file color.hpp.
Referenced by as_uint(), sdl::Pixel::set_color(), and sdl::Surface::set_colorkey().
as_uint() [2/2]
Uint32 sdl::Color::as_uint (Uint32 format) const inline
Return the color of the current object as a 32bit number (4 bytes)
Parameters
format pixel format to use
Definition at line 68 of file color.hpp.
References as_uint().
Black()
static constexpr Color sdl::Color::Black () inline static
Definition at line 91 of file color.hpp.
Blue()
static constexpr Color sdl::Color::Blue () inline static
Definition at line 94 of file color.hpp.
Green()
static constexpr Color sdl::Color::Green () inline static
Definition at line 93 of file color.hpp.
operator=() [1/2]
Color& sdl::Color::operator= (Color const &) default
Default copy assing operator.
Referenced by Color().
operator=() [2/2]
Color& sdl::Color::operator= (Color &&) default
Default move assing operator.
operator==()
bool sdl::Color::operator== (Color const & c) const inline
Return true if both colors are identical.
Definition at line 78 of file color.hpp.
Red()
static constexpr Color sdl::Color::Red () inline static
Definition at line 92 of file color.hpp.
Transparent()
static constexpr Color sdl::Color::Transparent () inline static
Definition at line 95 of file color.hpp.
White()
static constexpr Color sdl::Color::White () inline static
Definition at line 90 of file color.hpp.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, Color const & c) friend
Output stream overload that will print the value of the current color as a 4D vector of 8bit numbers.
Definition at line 84 of file color.hpp.
The documentation for this class was generated from the following file:
/home/runner/work/cpp-sdl2/cpp-sdl2/sources/cpp-sdl2/color.hpp