cpp-sdl2: sdl::Haptic::InstalledEffect Class Reference
sdl::Haptic::InstalledEffect Class Reference
Installed effect handle.
#include <haptic.hpp>
Public Member Functions
InstalledEffect (effect_list::size_type index, Haptic *owner)
InstalledEffect ()=default
InstalledEffect (InstalledEffect const &)
InstalledEffect & operator= (InstalledEffect const &)
InstalledEffect (InstalledEffect &&other) noexcept
InstalledEffect & operator= (InstalledEffect &&other) noexcept
~InstalledEffect ()
void run (uint32_t iterations=1)
Private Member Functions
void move_from (InstalledEffect &other)
Private Attributes
effect_list::size_type index_ = invalid_index
Haptic * owner_ = nullptr
Static Private Attributes
static constexpr effect_list::size_type invalid_index
Friends
class Haptic
Detailed Description
Installed effect handle.
Definition at line 27 of file haptic.hpp.
Constructor & Destructor Documentation
InstalledEffect() [1/4]
sdl::Haptic::InstalledEffect::InstalledEffect (effect_list::size_type index, Haptic * owner) inline
Definition at line 38 of file haptic.hpp.
References InstalledEffect(), and operator=().
InstalledEffect() [2/4]
sdl::Haptic::InstalledEffect::InstalledEffect () default
Referenced by InstalledEffect().
InstalledEffect() [3/4]
sdl::Haptic::InstalledEffect::InstalledEffect (InstalledEffect const &)
InstalledEffect() [4/4]
sdl::Haptic::InstalledEffect::InstalledEffect (InstalledEffect && other) inline noexcept
Definition at line 46 of file haptic.hpp.
~InstalledEffect()
sdl::Haptic::InstalledEffect::~InstalledEffect () inline
Definition at line 64 of file haptic.hpp.
References sdl::Haptic::get_effect_sdlid(), sdl::Haptic::ptr(), and sdl::Haptic::remove_effect().
Member Function Documentation
move_from()
void sdl::Haptic::InstalledEffect::move_from (InstalledEffect & other) inline private
Definition at line 35 of file haptic.hpp.
operator=() [1/2]
InstalledEffect& sdl::Haptic::InstalledEffect::operator= (InstalledEffect const &)
Referenced by InstalledEffect(), and sdl::Haptic::~Haptic().
operator=() [2/2]
InstalledEffect& sdl::Haptic::InstalledEffect::operator= (InstalledEffect && other) inline noexcept
Definition at line 51 of file haptic.hpp.
References index_, and invalid_index.
run()
void sdl::Haptic::InstalledEffect::run (uint32_t iterations = 1) inline
Definition at line 75 of file haptic.hpp.
References sdl::Haptic::run_effect().
Friends And Related Function Documentation
Haptic
friend class Haptic friend
Definition at line 33 of file haptic.hpp.
Referenced by sdl::Haptic::~Haptic().
Member Data Documentation
index_
effect_list::size_type sdl::Haptic::InstalledEffect::index_ = invalid_index private
Definition at line 31 of file haptic.hpp.
Referenced by sdl::Haptic::get_effect_sdlid(), and operator=().
invalid_index
constexpr effect_list::size_type sdl::Haptic::InstalledEffect::invalid_index static private
Initial value:
=
            std::numeric_limits<effect_list::size_type>::max()
Definition at line 29 of file haptic.hpp.
Referenced by operator=().
owner_
Haptic* sdl::Haptic::InstalledEffect::owner_ = nullptr private
Definition at line 32 of file haptic.hpp.
The documentation for this class was generated from the following file:
/home/runner/work/cpp-sdl2/cpp-sdl2/sources/cpp-sdl2/haptic.hpp