cpp-sdl2: sdl::Surface Class Reference
sdl::Surface Class Reference
Represent an SDL_Surface.
#include <surface.hpp>
Classes
class Lock
Represent a lock to safely access surface content.
Public Member Functions
Surface (SDL_Surface *surface)
Explicit converting ctor from C SDL_Surface to sdl::Surface.
Surface (Surface &&other) noexcept
Surface & operator= (Surface &&other) noexcept
Surface (Uint32 flags, int w, int h, int depth, Uint32 rmask, Uint32 gmask, Uint32 bmask, Uint32 amask)
Create surface for given parameters.
Surface (void *pixels, int w, int h, int depth, int pitch, Uint32 rmask, Uint32 gmask, Uint32 bmask, Uint32 amask)
Create surface from array of pixels.
Surface (Uint32 flags, int w, int h, int depth, Uint32 format)
Create surface with specified format.
Surface (void *pixels, int w, int h, int depth, int pitch, int format)
Create surface from array of pixels.
Surface (std::string const &filename)
Stubbed constructor for missing SDL_Image usage.
~Surface ()
RAII dtor to automatically free the surface.
SDL_Surface * ptr () const
Get C SDL_Surface object.
Surface with_format (SDL_PixelFormat const &format) const
Surface with_format (Uint32 format) const
Surface & convert_to (SDL_PixelFormat const &format)
Convert this surface to specified format.
Surface & convert_to (Uint32 format)
Convert this surface to specified format.
void blit_on (Rect const &src, Surface &surf, Rect const &dst) const
Blit surface on another.
void blit_on (Surface &surf, Rect const &dst) const
Blit surface on another.
int width () const
Get width of surface.
int height () const
Get height of surface.
Vec2i size () const
Get size of surface.
SDL_PixelFormat const & pixelformat () const
Get surface's pixel format.
Uint32 format () const
Get surface format.
Uint32 flags () const
Get surface flags.
Rect cliprect () const
Get surface clip rectangle.
void disable_colorkey () const
disable colorkey
void set_colorkey (Uint32 key) const
Set colorkey.
void set_colorkey (Color const &color) const
Set colorkey.
Color colorkey () const
Get color key.
void set_blendmode (SDL_BlendMode const &bm) const
Set surface blend mode.
SDL_BlendMode blendmode () const
void set_colormod (Color const &color) const
Set colormod.
void set_colormod (Uint8 r, Uint8 g, Uint8 b) const
Set colormod.
Color colormod () const
Get colormod.
void set_alphamod (Uint8 alpha) const
Set alphamod.
Uint8 alphamod () const
Get alphamod.
void set_coloralphamod (Uint8 r, Uint8 g, Uint8 b, Uint8 a) const
Set color and alpha mod.
void set_coloralphamod (Color const &c) const
Set color and alpha mod.
Color coloralphamod () const
Get color and alpha mod.
Lock lock ()
Private Attributes
SDL_Surface * surface_ = nullptr
Set surface pointer.
Detailed Description
Represent an SDL_Surface.
Definition at line 21 of file surface.hpp.
Constructor & Destructor Documentation
Surface() [1/7]
sdl::Surface::Surface (SDL_Surface * surface) inline explicit
Explicit converting ctor from C SDL_Surface to sdl::Surface.
Definition at line 59 of file surface.hpp.
Surface() [2/7]
sdl::Surface::Surface (Surface && other) inline noexcept
Definition at line 61 of file surface.hpp.
Surface() [3/7]
sdl::Surface::Surface (Uint32 flags, int w, int h, int depth, Uint32 rmask, Uint32 gmask, Uint32 bmask, Uint32 amask) inline
Create surface for given parameters.
Definition at line 75 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Surface() [4/7]
sdl::Surface::Surface (void * pixels, int w, int h, int depth, int pitch, Uint32 rmask, Uint32 gmask, Uint32 bmask, Uint32 amask) inline
Create surface from array of pixels.
Definition at line 91 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Surface() [5/7]
sdl::Surface::Surface (Uint32 flags, int w, int h, int depth, Uint32 format) inline
Create surface with specified format.
Definition at line 108 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Surface() [6/7]
sdl::Surface::Surface (void * pixels, int w, int h, int depth, int pitch, int format) inline
Create surface from array of pixels.
Definition at line 115 of file surface.hpp.
References sdl::Surface::Lock::Surface, and sdl::Surface::Lock::surface_.
Surface() [7/7]
sdl::Surface::Surface (std::string const & filename) inline
Stubbed constructor for missing SDL_Image usage.
Definition at line 131 of file surface.hpp.
~Surface()
sdl::Surface::~Surface () inline
RAII dtor to automatically free the surface.
Definition at line 144 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Member Function Documentation
alphamod()
Uint8 sdl::Surface::alphamod () const inline
Get alphamod.
Definition at line 298 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Referenced by coloralphamod().
blendmode()
SDL_BlendMode sdl::Surface::blendmode () const inline
Definition at line 262 of file surface.hpp.
References sdl::Surface::Lock::surface_.
blit_on() [1/2]
void sdl::Surface::blit_on (Rect const & src, Surface & surf, Rect const & dst) const inline
Blit surface on another.
Definition at line 180 of file surface.hpp.
References sdl::Surface::Lock::surface_, and surface_.
blit_on() [2/2]
void sdl::Surface::blit_on (Surface & surf, Rect const & dst) const inline
Blit surface on another.
Definition at line 191 of file surface.hpp.
References sdl::Surface::Lock::surface_, and surface_.
cliprect()
Rect sdl::Surface::cliprect () const inline
Get surface clip rectangle.
Definition at line 217 of file surface.hpp.
References sdl::Surface::Lock::surface_.
coloralphamod()
Color sdl::Surface::coloralphamod () const inline
Get color and alpha mod.
Definition at line 319 of file surface.hpp.
References alphamod(), and colormod().
colorkey()
Color sdl::Surface::colorkey () const inline
Get color key.
Definition at line 248 of file surface.hpp.
References pixelformat(), and sdl::Surface::Lock::surface_.
colormod()
Color sdl::Surface::colormod () const inline
Get colormod.
Definition at line 283 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Referenced by coloralphamod().
convert_to() [1/2]
Surface& sdl::Surface::convert_to (SDL_PixelFormat const & format) inline
Convert this surface to specified format.
Definition at line 168 of file surface.hpp.
References with_format().
convert_to() [2/2]
Surface& sdl::Surface::convert_to (Uint32 format) inline
Convert this surface to specified format.
Definition at line 173 of file surface.hpp.
References sdl::Surface::Lock::surface_, and with_format().
disable_colorkey()
void sdl::Surface::disable_colorkey () const inline
disable colorkey
Definition at line 225 of file surface.hpp.
References sdl::Surface::Lock::surface_.
flags()
Uint32 sdl::Surface::flags () const inline
Get surface flags.
Definition at line 214 of file surface.hpp.
References sdl::Surface::Lock::surface_.
format()
Uint32 sdl::Surface::format () const inline
Get surface format.
Definition at line 211 of file surface.hpp.
References sdl::Surface::Lock::surface_.
height()
int sdl::Surface::height () const inline
Get height of surface.
Definition at line 203 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Referenced by size().
lock()
Lock sdl::Surface::lock () inline
Lock surface for raw access to pixel. Return a lock object that permit to access the pixels. When lock goes out of scope, resources goes unlocked automatically
Definition at line 329 of file surface.hpp.
References sdl::Surface::Lock::surface_.
operator=()
Surface& sdl::Surface::operator= (Surface && other) inline noexcept
Definition at line 63 of file surface.hpp.
References sdl::Surface::Lock::surface_.
pixelformat()
SDL_PixelFormat const& sdl::Surface::pixelformat () const inline
Get surface's pixel format.
Definition at line 208 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Referenced by colorkey(), and set_colorkey().
ptr()
SDL_Surface* sdl::Surface::ptr () const inline
Get C SDL_Surface object.
Definition at line 147 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Referenced by sdl::Window::set_icon(), and sdl::Texture::Texture().
set_alphamod()
void sdl::Surface::set_alphamod (Uint8 alpha) const inline
Set alphamod.
Definition at line 292 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Referenced by set_coloralphamod().
set_blendmode()
void sdl::Surface::set_blendmode (SDL_BlendMode const & bm) const inline
Set surface blend mode.
Definition at line 257 of file surface.hpp.
References sdl::Surface::Lock::surface_.
set_coloralphamod() [1/2]
void sdl::Surface::set_coloralphamod (Uint8 r, Uint8 g, Uint8 b, Uint8 a) const inline
Set color and alpha mod.
Definition at line 307 of file surface.hpp.
References set_alphamod(), and set_colormod().
set_coloralphamod() [2/2]
void sdl::Surface::set_coloralphamod (Color const & c) const inline
Set color and alpha mod.
Definition at line 313 of file surface.hpp.
References set_alphamod(), and set_colormod().
set_colorkey() [1/2]
void sdl::Surface::set_colorkey (Uint32 key) const inline
Set colorkey.
Definition at line 232 of file surface.hpp.
References sdl::Surface::Lock::surface_.
set_colorkey() [2/2]
void sdl::Surface::set_colorkey (Color const & color) const inline
Set colorkey.
Definition at line 238 of file surface.hpp.
References sdl::Color::as_uint(), pixelformat(), and sdl::Surface::Lock::surface_.
set_colormod() [1/2]
void sdl::Surface::set_colormod (Color const & color) const inline
Set colormod.
Definition at line 271 of file surface.hpp.
Referenced by set_coloralphamod().
set_colormod() [2/2]
void sdl::Surface::set_colormod (Uint8 r, Uint8 g, Uint8 b) const inline
Set colormod.
Definition at line 276 of file surface.hpp.
References sdl::Surface::Lock::surface_.
size()
Vec2i sdl::Surface::size () const inline
Get size of surface.
Definition at line 205 of file surface.hpp.
References height(), and width().
width()
int sdl::Surface::width () const inline
Get width of surface.
Definition at line 201 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Referenced by size().
with_format() [1/2]
Surface sdl::Surface::with_format (SDL_PixelFormat const & format) const inline
Convert surface to given format
Parameters
format What pixel format to use
Definition at line 151 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Referenced by convert_to().
with_format() [2/2]
Surface sdl::Surface::with_format (Uint32 format) const inline
convert surface from given format
Parameters
format what format to use
Definition at line 160 of file surface.hpp.
References sdl::Surface::Lock::surface_.
Member Data Documentation
surface_
SDL_Surface* sdl::Surface::surface_ = nullptr private
Set surface pointer.
Definition at line 337 of file surface.hpp.
Referenced by blit_on().
The documentation for this class was generated from the following file:
/home/runner/work/cpp-sdl2/cpp-sdl2/sources/cpp-sdl2/surface.hpp