cpp-sdl2: sdl::GameController Class Reference
sdl::GameController Class Reference
Represent a gamepad (game controller)
#include <game_controller.hpp>
Public Member Functions
GameController (int joystick_index)
Construct a controller from a joystick index, throws if that index is not a game controller.
GameController (SDL_GameController *controller)
Construct a controller from a GameController pointer. This object will take ownership of the controller pointed.
GameController ()=default
Construct an empty controller.
GameController (GameController const &)=delete
Not copyable.
GameController & operator= (GameController const &)=delete
GameController (GameController &&other) noexcept
move ctor
GameController & operator= (GameController &&other) noexcept
move-assing operator
~GameController ()
Close the opened controller pointer, unless this wrapper was created via GameController::non_owning()
SDL_GameController * ptr () const
Get the SDL pointer.
Haptic open_haptic () const
Open the haptic device from the controller.
bool is_attached () const
Return true if this controller is attached.
int16_t get_axis (SDL_GameControllerAxis axis) const
Get the current imediate value of the given axis.
int8_t get_button (SDL_GameControllerButton button) const
Get the current imedate value of the given button.
std::string name () const
Static Public Member Functions
static std::string get_controller_name (int joystick_index)
static int load_mapping_database (std::string const &file_path)
Load a file database.
static int load_mapping_database (const char *file_path)
Load a file database.
static int add_mapping (std::string const &mapping_string)
Add a mapping string.
static int add_mapping (const char *mapping_string)
Add a mapping string.
static std::vector< GameController > open_all_available_controllers ()
Try to open all available controllers, and return an array of all controller sucessfully openned.
static GameController non_owning (SDL_JoystickID joystick_id)
Create a non_owning controller around a stick ID, to use the C++ API without managing the controller.
static GameController non_owning (SDL_GameController *controller)
Create a non_owning controller around an SDL controller pointer, to use the C++ aPI withiout managing the controller.
Private Member Functions
GameController (SDL_GameController *controller, bool non_owned)
Private controller for a non-onwer controller. The bool argument is expected to be false here.
Private Attributes
SDL_GameController * controller_ = nullptr
bool const owned_ = true
Detailed Description
Represent a gamepad (game controller)
Definition at line 14 of file game_controller.hpp.
Constructor & Destructor Documentation
GameController() [1/6]
sdl::GameController::GameController (int joystick_index) inline
Construct a controller from a joystick index, throws if that index is not a game controller.
Definition at line 18 of file game_controller.hpp.
References controller_.
GameController() [2/6]
sdl::GameController::GameController (SDL_GameController * controller) inline
Construct a controller from a GameController pointer. This object will take ownership of the controller pointed.
Definition at line 28 of file game_controller.hpp.
References GameController(), and operator=().
GameController() [3/6]
sdl::GameController::GameController () default
Construct an empty controller.
Referenced by GameController().
GameController() [4/6]
sdl::GameController::GameController (GameController const &) delete
Not copyable.
GameController() [5/6]
sdl::GameController::GameController (GameController && other) inline noexcept
move ctor
Definition at line 38 of file game_controller.hpp.
~GameController()
sdl::GameController::~GameController () inline
Close the opened controller pointer, unless this wrapper was created via GameController::non_owning()
Definition at line 65 of file game_controller.hpp.
References controller_, and owned_.
GameController() [6/6]
sdl::GameController::GameController (SDL_GameController * controller, bool non_owned) inline private
Private controller for a non-onwer controller. The bool argument is expected to be false here.
Definition at line 220 of file game_controller.hpp.
References owned_.
Member Function Documentation
add_mapping() [1/2]
static int sdl::GameController::add_mapping (std::string const & mapping_string) inline static
Add a mapping string.
Definition at line 163 of file game_controller.hpp.
add_mapping() [2/2]
static int sdl::GameController::add_mapping (const char * mapping_string) inline static
Add a mapping string.
Definition at line 169 of file game_controller.hpp.
get_axis()
int16_t sdl::GameController::get_axis (SDL_GameControllerAxis axis) const inline
Get the current imediate value of the given axis.
Definition at line 86 of file game_controller.hpp.
References controller_.
get_button()
int8_t sdl::GameController::get_button (SDL_GameControllerButton button) const inline
Get the current imedate value of the given button.
Definition at line 92 of file game_controller.hpp.
References controller_.
get_controller_name()
static std::string sdl::GameController::get_controller_name (int joystick_index) inline static
Definition at line 124 of file game_controller.hpp.
References name().
is_attached()
bool sdl::GameController::is_attached () const inline
Return true if this controller is attached.
Definition at line 80 of file game_controller.hpp.
References controller_.
load_mapping_database() [1/2]
static int sdl::GameController::load_mapping_database (std::string const & file_path) inline static
Load a file database.
Definition at line 145 of file game_controller.hpp.
load_mapping_database() [2/2]
static int sdl::GameController::load_mapping_database (const char * file_path) inline static
Load a file database.
Definition at line 151 of file game_controller.hpp.
name()
std::string sdl::GameController::name () const inline
Definition at line 117 of file game_controller.hpp.
References controller_.
Referenced by get_controller_name().
non_owning() [1/2]
static GameController sdl::GameController::non_owning (SDL_JoystickID joystick_id) inline static
Create a non_owning controller around a stick ID, to use the C++ API without managing the controller.
Definition at line 207 of file game_controller.hpp.
non_owning() [2/2]
static GameController sdl::GameController::non_owning (SDL_GameController * controller) inline static
Create a non_owning controller around an SDL controller pointer, to use the C++ aPI withiout managing the controller.
Definition at line 213 of file game_controller.hpp.
open_all_available_controllers()
static std::vector<GameController> sdl::GameController::open_all_available_controllers () inline static
Try to open all available controllers, and return an array of all controller sucessfully openned.
Definition at line 183 of file game_controller.hpp.
open_haptic()
Haptic sdl::GameController::open_haptic () const inline
Open the haptic device from the controller.
Definition at line 74 of file game_controller.hpp.
References controller_.
operator=() [1/2]
GameController& sdl::GameController::operator= (GameController const &) delete
Referenced by GameController().
operator=() [2/2]
GameController& sdl::GameController::operator= (GameController && other) inline noexcept
move-assing operator
Definition at line 44 of file game_controller.hpp.
References controller_, and owned_.
ptr()
SDL_GameController* sdl::GameController::ptr () const inline
Get the SDL pointer.
Definition at line 71 of file game_controller.hpp.
References controller_.
Member Data Documentation
controller_
SDL_GameController* sdl::GameController::controller_ = nullptr private
Definition at line 226 of file game_controller.hpp.
Referenced by GameController(), get_axis(), get_button(), is_attached(), name(), open_haptic(), operator=(), ptr(), and ~GameController().
owned_
bool const sdl::GameController::owned_ = true private
Definition at line 227 of file game_controller.hpp.
Referenced by GameController(), operator=(), and ~GameController().
The documentation for this class was generated from the following file:
/home/runner/work/cpp-sdl2/cpp-sdl2/sources/cpp-sdl2/game_controller.hpp