cpp-sdl2: sdl::Rect Class Reference
sdl::Rect Class Reference
Rect, C++ wrapping of SDL_Rect.
#include <rect.hpp>
Public Member Functions
constexpr Rect ()
Construct a Rect initialized at 0.
constexpr Rect (int x, int y, int w, int h)
constexpr Rect (Vec2i const &corner, Vec2i const &size)
constexpr Rect (SDL_Rect const &r)
Copy a Rect.
Rect (Rect const &) noexcept=default
Copy a Rect.
Rect (Rect &&) noexcept=default
Move from a Rect.
Rect & operator= (Rect const &) noexcept=default
Copy assign a Rect.
Rect & operator= (Rect &&) noexcept=default
Move assign a Rect.
bool operator== (Rect const &other) const
Returns true if the two rect are the same.
constexpr int x1 () const
Return the 'min X' position of the Rect.
constexpr int x2 () const
Return the 'max X' position of the Rect.
constexpr int y1 () const
Return the 'min Y' position of the Rect.
constexpr int y2 () const
Return the 'max Y' position of the Rect.
Vec2i botleft () const
Get the bottom left corner position.
Vec2i botright () const
Get the bottom right corner position.
Vec2i topleft () const
Get the top left corner position.
Vec2i topright () const
Get the top right corner position.
Vec2i size () const
Get the size of the Rect.
Vec2i center () const
Get the center of the Rect.
bool is_empty () const
Return true if this Rect is empty.
bool contains (int px, int py) const
bool contains (Vec2i const &point) const
bool intersects (Rect const &r) const
Return true if tthis rect intersct another rect.
bool intersect (Vec2i const &p1, Vec2i const &p2) const
Return true if this rect intersect the line.
Rect inter (Rect const &r) const
Return the intersction of the two rects.
Rect get_union (Rect const &r) const
Return the union of the two rects.
Static Public Member Functions
static constexpr Rect from_center (int cx, int cy, int w, int h)
static constexpr Rect from_center (Vec2i const &center, Vec2i const &size)
static constexpr Rect from_corners (int x1, int y1, int x2, int y2)
static constexpr Rect from_corners (Vec2i const &corner1, Vec2i const &corner2)
Detailed Description
Rect, C++ wrapping of SDL_Rect.
Definition at line 11 of file rect.hpp.
Constructor & Destructor Documentation
Rect() [1/6]
constexpr sdl::Rect::Rect () inline
Construct a Rect initialized at 0.
Definition at line 15 of file rect.hpp.
Referenced by from_corners().
Rect() [2/6]
constexpr sdl::Rect::Rect (int x, int y, int w, int h) inline
Construct a Rect with the given dimensions
Parameters
x Position on X axis
y Position on Y axis
w Size on X axis
h Size on Y axis
Definition at line 22 of file rect.hpp.
Rect() [3/6]
constexpr sdl::Rect::Rect (Vec2i const & corner, Vec2i const & size) inline
Construct a Rect with the giver dimensions
Parameters
corner X/Y position on screen as a 2D vector
size X/Y size on screen as a 2D vector
Definition at line 27 of file rect.hpp.
References size().
Rect() [4/6]
constexpr sdl::Rect::Rect (SDL_Rect const & r) inline
Copy a Rect.
Definition at line 33 of file rect.hpp.
Rect() [5/6]
sdl::Rect::Rect (Rect const &) default noexcept
Copy a Rect.
Rect() [6/6]
sdl::Rect::Rect (Rect &&) default noexcept
Move from a Rect.
Member Function Documentation
botleft()
Vec2i sdl::Rect::botleft () const inline
Get the bottom left corner position.
Definition at line 96 of file rect.hpp.
References x1(), and y1().
botright()
Vec2i sdl::Rect::botright () const inline
Get the bottom right corner position.
Definition at line 98 of file rect.hpp.
References x2(), and y1().
center()
Vec2i sdl::Rect::center () const inline
Get the center of the Rect.
Definition at line 107 of file rect.hpp.
Referenced by from_center().
contains() [1/2]
bool sdl::Rect::contains (int px, int py) const inline
Return true if this rect contains the given point
Parameters
px X position of the point
py Y position of the point
Definition at line 115 of file rect.hpp.
References x1(), y1(), and y2().
Referenced by contains().
contains() [2/2]
bool sdl::Rect::contains (Vec2i const & point) const inline
Return true if this rect contains the given point
Parameters
point The X/Y coordinates of the point as a vector 2D
Definition at line 122 of file rect.hpp.
References contains().
from_center() [1/2]
static constexpr Rect sdl::Rect::from_center (int cx, int cy, int w, int h) inline static
Contruct a Rect with dimensions around a center point
Parameters
cx position of the center on the X axis
cy position of the center on the Y axis
w Size on X axis
h Size on Y axis
Definition at line 46 of file rect.hpp.
from_center() [2/2]
static constexpr Rect sdl::Rect::from_center (Vec2i const & center, Vec2i const & size) inline static
Construct a Rect with dimensions around a center point
Parameters
center X/Y position of the center point as a 2D vector
Definition at line 53 of file rect.hpp.
References center(), and size().
from_corners() [1/2]
static constexpr Rect sdl::Rect::from_corners (int x1, int y1, int x2, int y2) inline static
Construct a rect from 2 conrer points
Parameters
x1 X position of first point
y1 Y position of first point
x2 X position of second point
x2 Y position of second point
Definition at line 63 of file rect.hpp.
References Rect(), x1(), x2(), y1(), and y2().
from_corners() [2/2]
static constexpr Rect sdl::Rect::from_corners (Vec2i const & corner1, Vec2i const & corner2) inline static
Definition at line 68 of file rect.hpp.
References Rect().
get_union()
Rect sdl::Rect::get_union (Rect const & r) const inline
Return the union of the two rects.
Definition at line 155 of file rect.hpp.
inter()
Rect sdl::Rect::inter (Rect const & r) const inline
Return the intersction of the two rects.
Definition at line 146 of file rect.hpp.
intersect()
bool sdl::Rect::intersect (Vec2i const & p1, Vec2i const & p2) const inline
Return true if this rect intersect the line.
Definition at line 134 of file rect.hpp.
intersects()
bool sdl::Rect::intersects (Rect const & r) const inline
Return true if tthis rect intersct another rect.
Definition at line 128 of file rect.hpp.
References x1(), x2(), y1(), and y2().
is_empty()
bool sdl::Rect::is_empty () const inline
Return true if this Rect is empty.
Definition at line 110 of file rect.hpp.
operator=() [1/2]
Rect& sdl::Rect::operator= (Rect const &) default noexcept
Copy assign a Rect.
operator=() [2/2]
Rect& sdl::Rect::operator= (Rect &&) default noexcept
Move assign a Rect.
operator==()
bool sdl::Rect::operator== (Rect const & other) const inline
Returns true if the two rect are the same.
Definition at line 81 of file rect.hpp.
size()
Vec2i sdl::Rect::size () const inline
Get the size of the Rect.
Definition at line 105 of file rect.hpp.
Referenced by from_center(), and Rect().
topleft()
Vec2i sdl::Rect::topleft () const inline
Get the top left corner position.
Definition at line 100 of file rect.hpp.
References x1(), and y2().
topright()
Vec2i sdl::Rect::topright () const inline
Get the top right corner position.
Definition at line 102 of file rect.hpp.
References x2(), and y2().
x1()
constexpr int sdl::Rect::x1 () const inline
Return the 'min X' position of the Rect.
Definition at line 87 of file rect.hpp.
Referenced by botleft(), contains(), from_corners(), intersects(), and topleft().
x2()
constexpr int sdl::Rect::x2 () const inline
Return the 'max X' position of the Rect.
Definition at line 89 of file rect.hpp.
Referenced by botright(), from_corners(), intersects(), and topright().
y1()
constexpr int sdl::Rect::y1 () const inline
Return the 'min Y' position of the Rect.
Definition at line 91 of file rect.hpp.
Referenced by botleft(), botright(), contains(), from_corners(), and intersects().
y2()
constexpr int sdl::Rect::y2 () const inline
Return the 'max Y' position of the Rect.
Definition at line 93 of file rect.hpp.
Referenced by contains(), from_corners(), intersects(), topleft(), and topright().
The documentation for this class was generated from the following file:
/home/leo/dev/cpp-sdl2/sources/rect.hpp