cpp-sdl2: sdl::Renderer Class Reference
sdl::Renderer Class Reference
Class that represent a SDL2 2D renderer.
#include <renderer.hpp>
Public Member Functions
Renderer (SDL_Renderer *renderer)
Construct a renderer from the SDL_Renderer C object.
Renderer ()
Default ctor, create an empty renderer object.
Renderer (Renderer &&other) noexcept
Default move ctor.
Renderer & operator= (Renderer &&other) noexcept
Move a renderer to this one.
~Renderer ()
Destroy the renderer automaticlally when object goes out of scope.
Renderer (Renderer const &)=delete
This is a managed RAII resource. this object is not copyable.
Renderer & operator= (Renderer const &)=delete
This is a managed RAII resource. this object is not copyable.
SDL_Renderer * ptr () const
Return a pointer to the wrapped C SDL_Renderer.
void get_info (SDL_RendererInfo &info) const
Populate renderinfo structure.
SDL_RendererInfo info () const
Get renderer infos.
Color drawcolor () const
void set_drawcolor (Uint8 r, Uint8 g, Uint8 b, Uint8 a=SDL_ALPHA_OPAQUE) const
Set the drawcolor from color values as bytes.
void set_drawcolor (Color const &c) const
Set the drawcolor from color struct.
Rect cliprect () const
Get the clipping rectangle.
void set_cliprect (Rect const &r) const
Set the clipping rectangle.
bool clip_enabled () const
Return true if clipping is enable.
void disable_clip () const
Disable the clipping rectangle.
bool intscale () const
Get the current integer scale.
void set_intscale (bool intscale) const
Set the integer scale.
Texture make_texture (Uint32 format, SDL_TextureAccess access, int w, int h) const
Make a new texture.
Texture make_texture (Uint32 format, SDL_TextureAccess access, Vec2i size) const
Make a new texture.
Texture make_texture (Surface const &surface) const
Make a texture from a surface.
Texture make_texture (std::string const &filename) const
void render_copy (Texture const &tex, Rect const &source_rect, Rect const &dest_rect) const
void present () const
Present renderer.
void clear () const
Clear renderer.
void clear (Color const &c) const
Clear with specified color.
void draw_line (Vec2i const &pos1, Vec2i const &pos2) const
Draw line between two points.
void draw_line (Vec2i const &pos1, Vec2i const &pos2, Color const &c) const
Draw line between two points with specified color.
void draw_lines (std::vector< Vec2i > const &points) const
Draw array of lines.
void draw_lines (std::vector< Vec2i > const &points, Color const &c) const
Draw array of lines with specified color.
void draw_point (Vec2i const &point) const
Draw point.
void draw_point (Vec2i const &point, Color const &c) const
Draw point with specified color.
void draw_points (std::vector< Vec2i > const &points) const
Draw array of points.
void draw_points (std::vector< Vec2i > const &points, Color const &c) const
Draw array of points with specified color.
void draw_ray (Vec2i const &orig, Vec2i const &ray) const
void draw_ray (Vec2i const &orig, Vec2i const &ray, Color const &c) const
void draw_rect (Rect const &rect) const
Draw rectangle.
void draw_rect (Rect const &rect, Color const &c) const
Draw rectangle with specified color.
void draw_rects (std::vector< Rect > const &rects) const
Draw array of rectangles.
void draw_rects (std::vector< Rect > const &rects, const Color &c) const
Draw array of rectangles with specified colors.
void fill_rect (Rect const &rect) const
Fill rectangle.
void fill_rect (Rect const &rect, Color const &c) const
Fill rectangle with specified color.
void fill_rects (std::vector< Rect > const &rects) const
Fill array of rectangles.
void fill_rects (std::vector< Rect > const &rects, Color const &c)
Fill array of rectangles with specified colors.
Private Attributes
SDL_Renderer * renderer_ = nullptr
Pointer to raw SDL_Renderer.
Detailed Description
Class that represent a SDL2 2D renderer.
Definition at line 18 of file renderer.hpp.
Constructor & Destructor Documentation
Renderer() [1/4]
sdl::Renderer::Renderer (SDL_Renderer * renderer) inline explicit
Construct a renderer from the SDL_Renderer C object.
Definition at line 22 of file renderer.hpp.
Renderer() [2/4]
sdl::Renderer::Renderer () inline
Default ctor, create an empty renderer object.
Definition at line 25 of file renderer.hpp.
Referenced by ~Renderer().
Renderer() [3/4]
sdl::Renderer::Renderer (Renderer && other) inline noexcept
Default move ctor.
Definition at line 28 of file renderer.hpp.
~Renderer()
sdl::Renderer::~Renderer () inline
Destroy the renderer automaticlally when object goes out of scope.
Definition at line 43 of file renderer.hpp.
References operator=(), Renderer(), and renderer_.
Renderer() [4/4]
sdl::Renderer::Renderer (Renderer const &) delete
This is a managed RAII resource. this object is not copyable.
Member Function Documentation
clear() [1/2]
void sdl::Renderer::clear () const inline
Clear renderer.
Definition at line 173 of file renderer.hpp.
References renderer_.
Referenced by clear().
clear() [2/2]
void sdl::Renderer::clear (Color const & c) const inline
Clear with specified color.
Definition at line 179 of file renderer.hpp.
References clear(), and set_drawcolor().
clip_enabled()
bool sdl::Renderer::clip_enabled () const inline
Return true if clipping is enable.
Definition at line 108 of file renderer.hpp.
References renderer_.
cliprect()
Rect sdl::Renderer::cliprect () const inline
Get the clipping rectangle.
Definition at line 93 of file renderer.hpp.
References renderer_.
disable_clip()
void sdl::Renderer::disable_clip () const inline
Disable the clipping rectangle.
Definition at line 111 of file renderer.hpp.
References renderer_.
draw_line() [1/2]
void sdl::Renderer::draw_line (Vec2i const & pos1, Vec2i const & pos2) const inline
Draw line between two points.
Definition at line 186 of file renderer.hpp.
References renderer_.
Referenced by draw_line(), and draw_ray().
draw_line() [2/2]
void sdl::Renderer::draw_line (Vec2i const & pos1, Vec2i const & pos2, Color const & c) const inline
Draw line between two points with specified color.
Definition at line 193 of file renderer.hpp.
References draw_line(), and set_drawcolor().
draw_lines() [1/2]
void sdl::Renderer::draw_lines (std::vector< Vec2i > const & points) const inline
Draw array of lines.
Definition at line 200 of file renderer.hpp.
References renderer_.
Referenced by draw_lines().
draw_lines() [2/2]
void sdl::Renderer::draw_lines (std::vector< Vec2i > const & points, Color const & c) const inline
Draw array of lines with specified color.
Definition at line 207 of file renderer.hpp.
References draw_lines(), and set_drawcolor().
draw_point() [1/2]
void sdl::Renderer::draw_point (Vec2i const & point) const inline
Draw point.
Definition at line 214 of file renderer.hpp.
References renderer_.
Referenced by draw_point().
draw_point() [2/2]
void sdl::Renderer::draw_point (Vec2i const & point, Color const & c) const inline
Draw point with specified color.
Definition at line 221 of file renderer.hpp.
References draw_point(), and set_drawcolor().
draw_points() [1/2]
void sdl::Renderer::draw_points (std::vector< Vec2i > const & points) const inline
Draw array of points.
Definition at line 228 of file renderer.hpp.
References renderer_.
Referenced by draw_points().
draw_points() [2/2]
void sdl::Renderer::draw_points (std::vector< Vec2i > const & points, Color const & c) const inline
Draw array of points with specified color.
Definition at line 236 of file renderer.hpp.
References draw_points(), and set_drawcolor().
draw_ray() [1/2]
void sdl::Renderer::draw_ray (Vec2i const & orig, Vec2i const & ray) const inline
Definition at line 242 of file renderer.hpp.
References draw_line().
draw_ray() [2/2]
void sdl::Renderer::draw_ray (Vec2i const & orig, Vec2i const & ray, Color const & c) const inline
Definition at line 246 of file renderer.hpp.
References draw_line().
draw_rect() [1/2]
void sdl::Renderer::draw_rect (Rect const & rect) const inline
Draw rectangle.
Definition at line 252 of file renderer.hpp.
References renderer_.
Referenced by draw_rect().
draw_rect() [2/2]
void sdl::Renderer::draw_rect (Rect const & rect, Color const & c) const inline
Draw rectangle with specified color.
Definition at line 259 of file renderer.hpp.
References draw_rect(), and set_drawcolor().
draw_rects() [1/2]
void sdl::Renderer::draw_rects (std::vector< Rect > const & rects) const inline
Draw array of rectangles.
Definition at line 266 of file renderer.hpp.
References renderer_.
Referenced by draw_rects().
draw_rects() [2/2]
void sdl::Renderer::draw_rects (std::vector< Rect > const & rects, const Color & c) const inline
Draw array of rectangles with specified colors.
Definition at line 272 of file renderer.hpp.
References draw_rects(), and set_drawcolor().
drawcolor()
Color sdl::Renderer::drawcolor () const inline
Definition at line 70 of file renderer.hpp.
References renderer_.
fill_rect() [1/2]
void sdl::Renderer::fill_rect (Rect const & rect) const inline
Fill rectangle.
Definition at line 279 of file renderer.hpp.
References renderer_.
Referenced by fill_rect().
fill_rect() [2/2]
void sdl::Renderer::fill_rect (Rect const & rect, Color const & c) const inline
Fill rectangle with specified color.
Definition at line 285 of file renderer.hpp.
References fill_rect(), and set_drawcolor().
fill_rects() [1/2]
void sdl::Renderer::fill_rects (std::vector< Rect > const & rects) const inline
Fill array of rectangles.
Definition at line 292 of file renderer.hpp.
References renderer_.
Referenced by fill_rects().
fill_rects() [2/2]
void sdl::Renderer::fill_rects (std::vector< Rect > const & rects, Color const & c) inline
Fill array of rectangles with specified colors.
Definition at line 298 of file renderer.hpp.
References fill_rects(), and set_drawcolor().
get_info()
void sdl::Renderer::get_info (SDL_RendererInfo & info) const inline
Populate renderinfo structure.
Definition at line 55 of file renderer.hpp.
References renderer_.
Referenced by info().
info()
SDL_RendererInfo sdl::Renderer::info () const inline
Get renderer infos.
Definition at line 62 of file renderer.hpp.
References get_info().
intscale()
bool sdl::Renderer::intscale () const inline
Get the current integer scale.
Definition at line 118 of file renderer.hpp.
References renderer_.
make_texture() [1/4]
Texture sdl::Renderer::make_texture (Uint32 format, SDL_TextureAccess access, int w, int h) const inline
Make a new texture.
Definition at line 128 of file renderer.hpp.
References renderer_.
make_texture() [2/4]
Texture sdl::Renderer::make_texture (Uint32 format, SDL_TextureAccess access, Vec2i size) const inline
Make a new texture.
Definition at line 135 of file renderer.hpp.
References renderer_.
make_texture() [3/4]
Texture sdl::Renderer::make_texture (Surface const & surface) const inline
Make a texture from a surface.
Definition at line 142 of file renderer.hpp.
References renderer_.
make_texture() [4/4]
Texture sdl::Renderer::make_texture (std::string const & filename) const inline
Make a texture from a file
Parameters
filename file path
Definition at line 149 of file renderer.hpp.
References renderer_.
operator=() [1/2]
Renderer& sdl::Renderer::operator= (Renderer && other) inline noexcept
Move a renderer to this one.
Definition at line 31 of file renderer.hpp.
References renderer_.
Referenced by ~Renderer().
operator=() [2/2]
Renderer& sdl::Renderer::operator= (Renderer const &) delete
This is a managed RAII resource. this object is not copyable.
present()
void sdl::Renderer::present () const inline
Present renderer.
Definition at line 170 of file renderer.hpp.
References renderer_.
ptr()
SDL_Renderer* sdl::Renderer::ptr () const inline
Return a pointer to the wrapped C SDL_Renderer.
Definition at line 52 of file renderer.hpp.
References renderer_.
Referenced by render_copy().
render_copy()
void sdl::Renderer::render_copy (Texture const & tex, Rect const & source_rect, Rect const & dest_rect) const inline
Definition at line 154 of file renderer.hpp.
References ptr(), and renderer_.
set_cliprect()
void sdl::Renderer::set_cliprect (Rect const & r) const inline
Set the clipping rectangle.
Definition at line 101 of file renderer.hpp.
References renderer_.
set_drawcolor() [1/2]
void sdl::Renderer::set_drawcolor (Uint8 r, Uint8 g, Uint8 b, Uint8 a = SDL_ALPHA_OPAQUE) const inline
Set the drawcolor from color values as bytes.
Definition at line 79 of file renderer.hpp.
References renderer_.
Referenced by clear(), draw_line(), draw_lines(), draw_point(), draw_points(), draw_rect(), draw_rects(), fill_rect(), fill_rects(), and set_drawcolor().
set_drawcolor() [2/2]
void sdl::Renderer::set_drawcolor (Color const & c) const inline
Set the drawcolor from color struct.
Definition at line 87 of file renderer.hpp.
References set_drawcolor().
set_intscale()
void sdl::Renderer::set_intscale (bool intscale) const inline
Set the integer scale.
Definition at line 121 of file renderer.hpp.
References renderer_.
Member Data Documentation
renderer_
SDL_Renderer* sdl::Renderer::renderer_ = nullptr private
Pointer to raw SDL_Renderer.
Definition at line 306 of file renderer.hpp.
Referenced by clear(), clip_enabled(), cliprect(), disable_clip(), draw_line(), draw_lines(), draw_point(), draw_points(), draw_rect(), draw_rects(), drawcolor(), fill_rect(), fill_rects(), get_info(), intscale(), make_texture(), operator=(), present(), ptr(), render_copy(), set_cliprect(), set_drawcolor(), set_intscale(), and ~Renderer().
The documentation for this class was generated from the following file:
/home/runner/work/cpp-sdl2/cpp-sdl2/sources/cpp-sdl2/renderer.hpp