cpp-sdl2: sdl::simd Namespace Reference
sdl::simd Namespace Reference
Namespaces
details
Classes
struct allocator
Allocator usable with standard containers.
struct deleter
deleter usable with std::unique_ptr<T>.
class deleter< T[]>
deleter usable with std::unique_ptr<T[]>.
struct memory_resource
memory_resource usable with std::pmr::polymorphic_allocator
Typedefs
template<typename T >
using unique_ptr = std::unique_ptr< T, simd::deleter< T > >
Functions
size_t get_alignment ()
Report the alignment this system needs for SIMD allocations.
void * alloc (size_t len)
Allocate memory in a SIMD-friendly way.
void free (void *ptr)
Deallocate memory obtained from sdl::simd::alloc().
template<typename T , typename... Args>
std::enable_if_t<!std::is_array_v< T >, unique_ptr< T > > make_unique (Args &&... args)
Equivalent of std::make_unique<T> that returns a simd::unique_ptr.
template<typename T , typename... Args>
std::enable_if_t< std::extent_v< T > !=0 > make_unique (Args &&... args)=delete
make_unique<T[N]> is deleted.
template<typename T >
auto make_unique (std::size_t count) -> std::enable_if_t< std::is_array_v< T > &&std::extent_v< T >==0
Allocate and default construct count elements.
for (std::size_t i=0;i< count;++i) new(mem+i) U
return unique_ptr< T > (mem, deleter< T >(count))
template<typename T , typename... Args>
std::enable_if<!std::is_array_v< T >, std::shared_ptr< T > > make_shared (Args &&... args)
Equivalent of std::make_shared<T> that uses simd-friendly storage.
Variables
auto unique_ptr< T >
allocator< U > a
auto * mem = a.allocate(count)
Typedef Documentation
unique_ptr
template<typename T > using sdl::simd::unique_ptr = typedef std::unique_ptr<T, simd::deleter<T> >
Definition at line 131 of file simd.hpp.
Function Documentation
alloc()
void* sdl::simd::alloc (size_t len) inline
Allocate memory in a SIMD-friendly way.
See SDL_SIMDAlloc for more info.
Definition at line 22 of file simd.hpp.
Referenced by sdl::simd::allocator< T >::allocate(), and sdl::simd::memory_resource::do_allocate().
for()
sdl::simd::for () new
free()
void sdl::simd::free (void * ptr) inline
Deallocate memory obtained from sdl::simd::alloc().
Definition at line 28 of file simd.hpp.
Referenced by sdl::simd::allocator< T >::deallocate(), sdl::simd::memory_resource::do_deallocate(), sdl::simd::deleter< T >::operator()(), and sdl::simd::deleter< T[]>::operator()().
get_alignment()
size_t sdl::simd::get_alignment () inline
Report the alignment this system needs for SIMD allocations.
See SDL_SIMDGetAlignment for more info.
Definition at line 15 of file simd.hpp.
make_shared()
template<typename T , typename... Args> std::enable_if<!std::is_array_v<T>, std::shared_ptr<T> > sdl::simd::make_shared (Args &&... args)
Equivalent of std::make_shared<T> that uses simd-friendly storage.
Definition at line 159 of file simd.hpp.
References a, sdl::simd::allocator< T >::allocate(), and mem.
make_unique() [1/3]
template<typename T , typename... Args> std::enable_if_t<!std::is_array_v<T>, unique_ptr<T> > sdl::simd::make_unique (Args &&... args) delete
Equivalent of std::make_unique<T> that returns a simd::unique_ptr.
make_unique<T[N]> is deleted.
Definition at line 135 of file simd.hpp.
References a, sdl::simd::allocator< T >::allocate(), and make_unique().
Referenced by make_unique().
make_unique() [2/3]
template<typename T , typename... Args> std::enable_if_t<std::extent_v<T> != 0> sdl::simd::make_unique (Args &&... args) delete
make_unique<T[N]> is deleted.
make_unique<T[N]> is deleted.
Definition at line 135 of file simd.hpp.
References a, sdl::simd::allocator< T >::allocate(), and make_unique().
Referenced by make_unique().
make_unique() [3/3]
template<typename T > auto sdl::simd::make_unique (std::size_t count) -> std::enable_if_t<std::is_array_v<T> && std::extent_v<T> = pure virtual
Allocate and default construct count elements.
unique_ptr< T >()
return sdl::simd::unique_ptr< T > (mem , deleter< T > count)
Variable Documentation
a
allocator<U> sdl::simd::a
Definition at line 151 of file simd.hpp.
Referenced by sdl::Texture::access(), sdl::Color::as_uint(), sdl::Color::Color(), make_shared(), make_unique(), sdl::Color::operator==(), and sdl::Renderer::set_drawcolor().
mem
auto* sdl::simd::mem = a.allocate(count)
Definition at line 152 of file simd.hpp.
Referenced by sdl::simd::allocator< T >::allocate(), and make_shared().
unique_ptr< T >
auto sdl::simd::unique_ptr< T >
Initial value:
{
    using U = std::remove_extent_t<T>
Definition at line 149 of file simd.hpp.