cpp-sdl2: sdl Namespace Reference
sdl Namespace Reference
Define to deactivate exception support.
Namespaces
details
Contains implementation details.
Classes
class Color
C++ wrapping around the SDL_Color structure.
union Event
Object that reprent an event captured by SDL.
struct EventFilter
Event filter object.
class Exception
Define to deactivate exception support.
class Pixel
Represent a 4 channel pixel.
class Rect
Rect, C++ wrapping of SDL_Rect.
class Renderer
Class that represent a SDL2 2D renderer.
class Root
This class represent the "library entry point". Create and keep an instance of this object before creating any other sdl object (e.g. sdl::Window)
class SharedObject
Represent a shared object (dynamic library, dynamically loaded library, module, plugin...).
class Surface
Represent an SDL_Surface.
class Texture
Class that represet a renderer texture.
class Vec2
Generic tempated 2D vector class.
class Window
Represent an SDL window. Also contains accessor to any window related adjacent functionality like OpenGL/Vulkan helper functions.
Typedefs
using Vec2i = Vec2< int, SDL_Point >
Vector of two integers, that is convertible to/from SDL_Point.
using Vec2f = Vec2< float >
Vector of two floats.
using Vec2d = Vec2< double >
Vector of two double.
Functions
bool has_events ()
Return true if there are events in the queue.
bool has_events (Uint32 type)
bool has_events (Uint32 minType, Uint32 maxType)
void pump_events ()
void flush_events (Uint32 minType, Uint32 maxType)
void flush_events ()
Clear all events from the event queue.
void flush_events (Uint32 type)
Clear events from a specific type from the event queue.
void add_events (std::vector< Event > const &events, Uint32 minType, Uint32 maxType)
void add_events (std::vector< Event > const &events)
Add events to the queue.
void add_events (std::vector< Event > const &events, Uint32 type)
Add events of a specific type to the queue.
std::vector< Event > peek_events (size_t maxEvents, Uint32 minType, Uint32 maxType)
std::vector< Event > peek_events (size_t maxEvents)
Peek at future events.
std::vector< Event > peek_events (size_t maxEvents, Uint32 type)
std::vector< Event > get_events (size_t maxEvents, Uint32 minType, Uint32 maxType)
std::vector< Event > get_events (size_t maxEvents)
std::vector< Event > get_events (size_t maxEvents, Uint32 type)
Event::State event_state (Uint32 type)
void set_event_state (Uint32 type, Event::State state)
Detailed Description
Define to deactivate exception support.
Typedef Documentation
Vec2d
using sdl::Vec2d = typedef Vec2<double>
Vector of two double.
Definition at line 185 of file vec2.hpp.
Vec2f
using sdl::Vec2f = typedef Vec2<float>
Vector of two floats.
Definition at line 183 of file vec2.hpp.
Vec2i
using sdl::Vec2i = typedef Vec2<int, SDL_Point>
Vector of two integers, that is convertible to/from SDL_Point.
Definition at line 181 of file vec2.hpp.
Function Documentation
add_events() [1/3]
void sdl::add_events (std::vector< Event > const & events, Uint32 minType, Uint32 maxType) inline
Definition at line 222 of file event.hpp.
Referenced by add_events().
add_events() [2/3]
void sdl::add_events (std::vector< Event > const & events) inline
Add events to the queue.
Definition at line 237 of file event.hpp.
References add_events().
add_events() [3/3]
void sdl::add_events (std::vector< Event > const & events, Uint32 type) inline
Add events of a specific type to the queue.
Definition at line 243 of file event.hpp.
References add_events().
event_state()
Event::State sdl::event_state (Uint32 type) inline
Definition at line 361 of file event.hpp.
flush_events() [1/3]
void sdl::flush_events (Uint32 minType, Uint32 maxType) inline
Clear events of a range of types from the event queue
Parameters
minType lower type boundary of the range
maxType upper type boundary of the range
Definition at line 204 of file event.hpp.
Referenced by flush_events().
flush_events() [2/3]
void sdl::flush_events () inline
Clear all events from the event queue.
Definition at line 210 of file event.hpp.
References flush_events().
flush_events() [3/3]
void sdl::flush_events (Uint32 type) inline
Clear events from a specific type from the event queue.
Definition at line 216 of file event.hpp.
References flush_events().
get_events() [1/3]
std::vector<Event> sdl::get_events (size_t maxEvents, Uint32 minType, Uint32 maxType) inline
Get events from the queue maxEvents max number of events to get
Parameters
minType lower bound of type range
maxType upper bound of type range
Definition at line 282 of file event.hpp.
Referenced by get_events().
get_events() [2/3]
std::vector<Event> sdl::get_events (size_t maxEvents) inline
Get events from the queue
Parameters
type The type of events to look for
maxEvents max number of events to get
Definition at line 298 of file event.hpp.
References get_events().
get_events() [3/3]
std::vector<Event> sdl::get_events (size_t maxEvents, Uint32 type) inline
Get events from a specific type
Parameters
type The type of events to look for
maxEvents max number of events to get
Definition at line 306 of file event.hpp.
References get_events().
has_events() [1/3]
bool sdl::has_events () inline
Return true if there are events in the queue.
Definition at line 174 of file event.hpp.
has_events() [2/3]
bool sdl::has_events (Uint32 type) inline
Return true if there are events of a specific type in the queue
Parameters
type the type of the events you want to check for
Definition at line 181 of file event.hpp.
has_events() [3/3]
bool sdl::has_events (Uint32 minType, Uint32 maxType) inline
Return true if there are events of a specific range of types in the queue
Parameters
minType lower type boundary of the range
maxType upper type boundary of the range
Definition at line 189 of file event.hpp.
peek_events() [1/3]
std::vector<Event> sdl::peek_events (size_t maxEvents, Uint32 minType, Uint32 maxType) inline
Peek at multiple future events
Parameters
maxEvents max number of events to get
minType lower bound of event type range
maxType upper bound of event type range
Definition at line 252 of file event.hpp.
Referenced by peek_events().
peek_events() [2/3]
std::vector<Event> sdl::peek_events (size_t maxEvents) inline
Peek at future events.
Definition at line 266 of file event.hpp.
References peek_events().
peek_events() [3/3]
std::vector<Event> sdl::peek_events (size_t maxEvents, Uint32 type) inline
Peek events from a specific type
Parameters
type The type of events to look for
Definition at line 273 of file event.hpp.
References peek_events().
pump_events()
void sdl::pump_events () inline
Pump the event loop from the OS enent system. only call this from the main thread (or the thread taht initialized the video/window systems) This is only usefull if you aren't polling or waiting for events
Definition at line 196 of file event.hpp.
set_event_state()
void sdl::set_event_state (Uint32 type, Event::State state) inline
Definition at line 366 of file event.hpp.