cpp-sdl2: sdl::EventFilter Struct Reference
sdl::EventFilter Struct Reference
Event filter object.
#include <event.hpp>
Public Types
using func_type = bool(*)(void *, Event &)
Public Member Functions
EventFilter (func_type filter, void *userdata)
EventFilter (func_type filter)
~EventFilter ()
void filter_queue ()
void set ()
void add_watcher ()
void del_watcher ()
Static Public Member Functions
static int call_filter (void *data, SDL_Event *event)
static void unset ()
Public Attributes
void * userdata = nullptr
func_type filter = nullptr
bool is_watcher = false
Detailed Description
Event filter object.
Definition at line 316 of file event.hpp.
Member Typedef Documentation
func_type
using sdl::EventFilter::func_type = bool (*)(void*, Event&)
Definition at line 318 of file event.hpp.
Constructor & Destructor Documentation
EventFilter() [1/2]
sdl::EventFilter::EventFilter (func_type filter, void * userdata) inline
Definition at line 324 of file event.hpp.
References filter.
EventFilter() [2/2]
sdl::EventFilter::EventFilter (func_type filter) inline
Definition at line 329 of file event.hpp.
References filter.
~EventFilter()
sdl::EventFilter::~EventFilter () inline
Definition at line 331 of file event.hpp.
References del_watcher(), and is_watcher.
Member Function Documentation
add_watcher()
void sdl::EventFilter::add_watcher () inline
Definition at line 348 of file event.hpp.
References call_filter(), and is_watcher.
call_filter()
static int sdl::EventFilter::call_filter (void * data, SDL_Event * event) inline static
Definition at line 336 of file event.hpp.
References filter, and sdl::Event::ref_from().
Referenced by add_watcher(), del_watcher(), filter_queue(), and set().
del_watcher()
void sdl::EventFilter::del_watcher () inline
Definition at line 354 of file event.hpp.
References call_filter(), and is_watcher.
Referenced by ~EventFilter().
filter_queue()
void sdl::EventFilter::filter_queue () inline
Definition at line 342 of file event.hpp.
References call_filter().
set()
void sdl::EventFilter::set () inline
Definition at line 344 of file event.hpp.
References call_filter(), and userdata.
unset()
static void sdl::EventFilter::unset () inline static
Definition at line 346 of file event.hpp.
Member Data Documentation
filter
func_type sdl::EventFilter::filter = nullptr
Definition at line 321 of file event.hpp.
Referenced by call_filter(), and EventFilter().
is_watcher
bool sdl::EventFilter::is_watcher = false
Definition at line 322 of file event.hpp.
Referenced by add_watcher(), del_watcher(), and ~EventFilter().
userdata
void* sdl::EventFilter::userdata = nullptr
Definition at line 320 of file event.hpp.
Referenced by set().
The documentation for this struct was generated from the following file:
/home/leo/dev/cpp-sdl2/sources/event.hpp