name: examples

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04]
#       vulkan_ver: [ 1.1.114.0 ]
        sdl2_ver: [ 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14 ]
        include:
          - os: windows-latest
            os_family: windows
            vcpkg_triplet: x64-windows

          - os: ubuntu-20.04
            os_family: linux
            vcpkg_triplet: x64-linux

#   env:
#     VULKAN_BASE_URL: https://sdk.lunarg.com/sdk/download/${{matrix.vulkan_ver}}/${{matrix.os_family}}

    steps:
      - uses: actions/checkout@v2

#     - name: install vulkan (windows)
#       if: matrix.os_family == 'windows'
#       env:
#         VULKAN_URL: ${{env.VULKAN_BASE_URL}}/VulkanSDK-${{matrix.vulkan_ver}}-Installer.exe
#       run: |
#         echo "Downloading SDK ..."
#         Invoke-WebRequest "${env:VULKAN_URL}?Human=true" -OutFile VulkanSDK.exe -v
#         echo "Installing SDK ..."
#         Start-Process .\VulkanSDK.exe /S -Wait
#         echo "::set-env name=VULKAN_SDK::C:\VulkanSDK\${{matrix.vulkan_ver}}"


#     - name: install vulkan (linux)
#       if: matrix.os_family == 'linux'
#       env:
#         VULKAN_URL: ${{env.VULKAN_BASE_URL}}/vulkansdk-linux-x86_64-${{matrix.vulkan_ver}}.tar.gz
#       run: |
#         mkdir vulkan
#         cd vulkan
#         echo "Downloading SDK ..."
#         wget -qO vulkansdk.tar.gz "$VULKAN_URL"
#         tar xf vulkansdk.tar.gz
#         cd ..
#         echo "::set-env name=VULKAN_SDK::${{github.workspace}}/vcpkg"

      - name: setup vcpkg
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          echo '{
            "name":"cpp_sdl2",
            "version-string": "sdl${{matrix.sdl2_ver}}_vk${{matrix.vulkan_ver}}",
            "builtin-baseline": "5459adf5decc9e64b7f0cf3b1ab57e2f2a636a87",
            "dependencies": [
              {
                "name": "sdl2",
                "version-string": "${{matrix.sdl2_ver}}"
              },
              { "name": "opengl" }
            ]
          }' > vcpkg.json

      - name: cmake configure
        env:
          VCPKG_FEATURE_FLAGS: versions
        run: cmake -B build -DDCMAKE_TOOLCHAIN_FILE="./vcpkg/scripts/buildsystems/vcpkg.cmake" -DCPP_SDL2_BUILD_EXAMPLES=ON -DCPP_SDL2_ENABLE_OPENGL=ON

      - name: cmake build
        run: cmake --build build
