name: doc

on:
  push:
    branches: [trunk]

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get doxygen
        run: sudo apt-get install doxygen
      - name: build documentation
        run: |
          cd doxygen
          mkdir output
          doxygen Doxyfile
          cd ..
      - name: upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: doxygen/output/html
      - name: upload readme
        uses: actions/upload-artifact@v2
        with:
          name: readme
          path: README.md

  push-doc:
    runs-on: ubuntu-latest
    needs: build-doc
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: reset to previous state
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git reset --hard HEAD~1
          rm -rf index.md doc
      - name: download documentation
        uses: actions/download-artifact@v2
        with:
          name: documentation
          path: doc
      - name: download readme
        uses: actions/download-artifact@v2
        with:
          name: readme
      - name: push documentation
        run: |
          mv README.md index.md
          git add index.md doc
          git commit -m ':robot: :gear: :black_nib: :green_book: :point_right: :octocat: :computer: :thumbsup:'
          git push --force origin gh-pages
