name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    env:
      VULKAN_SDK_VER: 1.1.114.0
      VCPKG_VER: 2020.06

    steps:
      - uses: actions/checkout@v2

      - name: set environment
        run: |
          echo "::set-env name=VULKAN_SDK::C:\VulkanSDK\$env:VULKAN_SDK_VER"
          echo "::set-env name=VULKAN_SDK_URL::https://sdk.lunarg.com/sdk/download/$env:VULKAN_SDK_VER/windows/VulkanSDK-$env:VULKAN_SDK_VER-Installer.exe"
          echo "::set-env name=VCPKG_PATH::${{github.workspace}}/vcpkg"

      # TODO: for some reason, this always fail, taking time for nothing
      # - name: cache vulkan sdk
      #   id: cache-vulkan
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{env.VULKAN_SDK}}
      #     key: vulkan-${{env.VULKAN_SDK_VER}}

      - name: install vulkan sdk
        # if: steps.cache-vulkan.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest "${env:VULKAN_SDK_URL}?Human=true" -OutFile VulkanSDK.exe -v
          echo "Installing SDK ..."
          Start-Process .\VulkanSDK.exe /S -Wait

      - name: cache dependencies
        id: cache-vcpkg
        uses: actions/cache@v2
        with:
          path: ${{env.VCPKG_PATH}}
          key: vcpkg-${{env.VCPKG_VER}}-vk-${{env.VULKAN_SDK_VER}}

      - name: install dependencies
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          git checkout --force $env:VULKAN_VER
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install sdl2[*]:x64-windows
          cd ${{github.workspace}}

      - name: configure cmake
        run: cmake -B build -G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_PATH/scripts/buildsystems/vcpkg.cmake" -DCPP_SDL2_BUILD_EXAMPLES=ON -DCPP_SDL2_ENABLE_OPENGL=ON -DCPP_SDL2_ENABLE_VULKAN=ON

      - name: build
        run: cmake --build build
